version: 1.2
workflows:
   -  name: alphaSat-HMMER
      subclass: WDL
      testParameterFiles:
         - /alphaSat-HMMER/test/alphaSat-HMMER-local.json
      primaryDescriptorPath: alphaSat-HMMER/alphaSat-HMMER.wdl
  -  name: identify-hSat2and3
      subclass: WDL
      testParameterFiles:
         - /identify-hSat2and3/test/identify-hSat2and3-local.json
      primaryDescriptorPath: identify-hSat2and3/identify-hSat2and3.wdl
  -  name: extractAssemblyContigsInRegion
      subclass: WDL
      primaryDescriptorPath: tools/extractAssemblyContigsInRegion/extractAssemblyContigsInRegion.wdl
  -  name: ntrprism-to-bedgraph
      subclass: WDL
      primaryDescriptorPath: NTRprism/ntrprism_to_bedgraph.wdl
  -  name: fastaKmerCount
      subclass: WDL
      primaryDescriptorPath: tools/fastaKmerCount/fastaKmerCount.wdl
